# Generated by Django 4.1.7 on 2023-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloging', '0003_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_string',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
